title: Your Friends Favourite Music Curator 
author: Austin B 
email: kasetunes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I make Playlists
# social links
twitter_username: Kasetunes # DO NOT include the @ character, or else the build will fail!
github_username:  AustinBwanika # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
